export type Soft3DIconName =
  | "navigationHome"
  | "navigationLearn"
  | "navigationPractice"
  | "navigationReview"
  | "navigationProgress"
  | "navigationSettings"
  | "brandMission"
  | "skillUxUi"
  | "skillProductDesign"
  | "skillCreativeThinking"
  | "skillArtDirection"
  | "skillUxWriting"
  | "skillGraphicDesign"
  | "skillIelts"
  | "skillEnglishWork"
  | "skillCommunication"
  | "skillCriticalThinking"
  | "skillDesignOps"
  | "skillUxResearch"
  | "skillStockInvesting"
  | "skillThaiTax"
  | "skillDataAnalysis"
  | "skillProjectManagement"
  | "actionHint"
  | "actionTranslation"
  | "actionSubmit"
  | "actionNext"
  | "actionPrevious"
  | "actionZoom"
  | "actionSave"
  | "actionBookmark"
  | "actionNote"
  | "statusXp"
  | "statusStreak"
  | "statusCorrect"
  | "statusIncorrect"
  | "statusReviewDue"
  | "statusCompleted"
  | "statusInProgress"
  | "statusLocked"
  | "statusMastered"
  | "statusLevelUp"
  | "statusGoal"
  | "statusAccuracy";

export type Soft3DIconSize = "xs" | "nav" | "navLg" | "sm" | "md" | "brand" | "lg" | "xl";

export type MetallicIconCategory = "navigation" | "action" | "status" | "learningPath" | "hero";

export type MetallicIconTone = "silver" | "blue" | "mint" | "violet" | "champagne" | "graphite";
